// Package sourcepb carries the wire types for the reader's out-of-process
// feed-source plugins. The SourceProvider service mirrors source.Provider
// (Kind + Feed) and ItemMsg/MediaMsg mirror source.Item/source.Media, so a
// plugin binary can serve normalized items to the host over gRPC.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: internal/sourceplugin/grpc/provider.proto

package sourcepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SourceProvider_Kind_FullMethodName = "/sourceplugin.v1.SourceProvider/Kind"
	SourceProvider_Feed_FullMethodName = "/sourceplugin.v1.SourceProvider/Feed"
)

// SourceProviderClient is the client API for SourceProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SourceProvider is the gRPC face of source.Provider.
type SourceProviderClient interface {
	Kind(ctx context.Context, in *KindRequest, opts ...grpc.CallOption) (*KindReply, error)
	Feed(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedReply, error)
}

type sourceProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewSourceProviderClient(cc grpc.ClientConnInterface) SourceProviderClient {
	return &sourceProviderClient{cc}
}

func (c *sourceProviderClient) Kind(ctx context.Context, in *KindRequest, opts ...grpc.CallOption) (*KindReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KindReply)
	err := c.cc.Invoke(ctx, SourceProvider_Kind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceProviderClient) Feed(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedReply)
	err := c.cc.Invoke(ctx, SourceProvider_Feed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SourceProviderServer is the server API for SourceProvider service.
// All implementations must embed UnimplementedSourceProviderServer
// for forward compatibility.
//
// SourceProvider is the gRPC face of source.Provider.
type SourceProviderServer interface {
	Kind(context.Context, *KindRequest) (*KindReply, error)
	Feed(context.Context, *FeedRequest) (*FeedReply, error)
	mustEmbedUnimplementedSourceProviderServer()
}

// UnimplementedSourceProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSourceProviderServer struct{}

func (UnimplementedSourceProviderServer) Kind(context.Context, *KindRequest) (*KindReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Kind not implemented")
}
func (UnimplementedSourceProviderServer) Feed(context.Context, *FeedRequest) (*FeedReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Feed not implemented")
}
func (UnimplementedSourceProviderServer) mustEmbedUnimplementedSourceProviderServer() {}
func (UnimplementedSourceProviderServer) testEmbeddedByValue()                        {}

// UnsafeSourceProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SourceProviderServer will
// result in compilation errors.
type UnsafeSourceProviderServer interface {
	mustEmbedUnimplementedSourceProviderServer()
}

func RegisterSourceProviderServer(s grpc.ServiceRegistrar, srv SourceProviderServer) {
	// If the following call panics, it indicates UnimplementedSourceProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SourceProvider_ServiceDesc, srv)
}

func _SourceProvider_Kind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceProviderServer).Kind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceProvider_Kind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceProviderServer).Kind(ctx, req.(*KindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceProvider_Feed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceProviderServer).Feed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceProvider_Feed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceProviderServer).Feed(ctx, req.(*FeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SourceProvider_ServiceDesc is the grpc.ServiceDesc for SourceProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SourceProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sourceplugin.v1.SourceProvider",
	HandlerType: (*SourceProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Kind",
			Handler:    _SourceProvider_Kind_Handler,
		},
		{
			MethodName: "Feed",
			Handler:    _SourceProvider_Feed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/sourceplugin/grpc/provider.proto",
}
