// Package sourcepb carries the wire types for the reader's out-of-process
// feed-source plugins. The SourceProvider service mirrors source.Provider
// (Kind + Feed) and ItemMsg/MediaMsg mirror source.Item/source.Media, so a
// plugin binary can serve normalized items to the host over gRPC.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: internal/sourceplugin/grpc/provider.proto

package sourcepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MediaMsg mirrors source.Media: one attachment on an item.
type MediaMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // source.MediaKind
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	AltText       string                 `protobuf:"bytes,5,opt,name=alt_text,json=altText,proto3" json:"alt_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaMsg) Reset() {
	*x = MediaMsg{}
	mi := &file_internal_sourceplugin_grpc_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaMsg) ProtoMessage() {}

func (x *MediaMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sourceplugin_grpc_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaMsg.ProtoReflect.Descriptor instead.
func (*MediaMsg) Descriptor() ([]byte, []int) {
	return file_internal_sourceplugin_grpc_provider_proto_rawDescGZIP(), []int{0}
}

func (x *MediaMsg) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MediaMsg) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *MediaMsg) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaMsg) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MediaMsg) GetAltText() string {
	if x != nil {
		return x.AltText
	}
	return ""
}

// ItemMsg mirrors source.Item: one normalized entry. Every serializable field
// of source.Item is represented so the round trip is lossless.
type ItemMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // source.Kind
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Body          string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Permalink     string                 `protobuf:"bytes,7,opt,name=permalink,proto3" json:"permalink,omitempty"`
	Link          string                 `protobuf:"bytes,8,opt,name=link,proto3" json:"link,omitempty"`
	Media         []*MediaMsg            `protobuf:"bytes,9,rep,name=media,proto3" json:"media,omitempty"`
	Score         int32                  `protobuf:"varint,10,opt,name=score,proto3" json:"score,omitempty"`
	Comments      int32                  `protobuf:"varint,11,opt,name=comments,proto3" json:"comments,omitempty"`
	Created       int64                  `protobuf:"varint,12,opt,name=created,proto3" json:"created,omitempty"`
	Nsfw          bool                   `protobuf:"varint,13,opt,name=nsfw,proto3" json:"nsfw,omitempty"`
	Pinned        bool                   `protobuf:"varint,14,opt,name=pinned,proto3" json:"pinned,omitempty"`
	Tags          []string               `protobuf:"bytes,15,rep,name=tags,proto3" json:"tags,omitempty"`
	GroupCount    int32                  `protobuf:"varint,16,opt,name=group_count,json=groupCount,proto3" json:"group_count,omitempty"`
	GroupHigh     int32                  `protobuf:"varint,17,opt,name=group_high,json=groupHigh,proto3" json:"group_high,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemMsg) Reset() {
	*x = ItemMsg{}
	mi := &file_internal_sourceplugin_grpc_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemMsg) ProtoMessage() {}

func (x *ItemMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sourceplugin_grpc_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemMsg.ProtoReflect.Descriptor instead.
func (*ItemMsg) Descriptor() ([]byte, []int) {
	return file_internal_sourceplugin_grpc_provider_proto_rawDescGZIP(), []int{1}
}

func (x *ItemMsg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemMsg) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ItemMsg) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ItemMsg) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ItemMsg) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ItemMsg) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ItemMsg) GetPermalink() string {
	if x != nil {
		return x.Permalink
	}
	return ""
}

func (x *ItemMsg) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *ItemMsg) GetMedia() []*MediaMsg {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *ItemMsg) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ItemMsg) GetComments() int32 {
	if x != nil {
		return x.Comments
	}
	return 0
}

func (x *ItemMsg) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ItemMsg) GetNsfw() bool {
	if x != nil {
		return x.Nsfw
	}
	return false
}

func (x *ItemMsg) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *ItemMsg) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ItemMsg) GetGroupCount() int32 {
	if x != nil {
		return x.GroupCount
	}
	return 0
}

func (x *ItemMsg) GetGroupHigh() int32 {
	if x != nil {
		return x.GroupHigh
	}
	return 0
}

// KindRequest is the (empty) argument of SourceProvider.Kind.
type KindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KindRequest) Reset() {
	*x = KindRequest{}
	mi := &file_internal_sourceplugin_grpc_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KindRequest) ProtoMessage() {}

func (x *KindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sourceplugin_grpc_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KindRequest.ProtoReflect.Descriptor instead.
func (*KindRequest) Descriptor() ([]byte, []int) {
	return file_internal_sourceplugin_grpc_provider_proto_rawDescGZIP(), []int{2}
}

// KindReply carries the plugin's source.Kind as a string.
type KindReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KindReply) Reset() {
	*x = KindReply{}
	mi := &file_internal_sourceplugin_grpc_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KindReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KindReply) ProtoMessage() {}

func (x *KindReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sourceplugin_grpc_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KindReply.ProtoReflect.Descriptor instead.
func (*KindReply) Descriptor() ([]byte, []int) {
	return file_internal_sourceplugin_grpc_provider_proto_rawDescGZIP(), []int{3}
}

func (x *KindReply) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// FeedRequest mirrors source.Query.
type FeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Sort          string                 `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedRequest) Reset() {
	*x = FeedRequest{}
	mi := &file_internal_sourceplugin_grpc_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedRequest) ProtoMessage() {}

func (x *FeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sourceplugin_grpc_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedRequest.ProtoReflect.Descriptor instead.
func (*FeedRequest) Descriptor() ([]byte, []int) {
	return file_internal_sourceplugin_grpc_provider_proto_rawDescGZIP(), []int{4}
}

func (x *FeedRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *FeedRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *FeedRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *FeedRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// FeedReply mirrors source.Result plus a transported error string: a non-empty
// error means the plugin's Feed failed and the host reconstitutes a Go error
// from it (so a provider error crosses the process boundary cleanly).
type FeedReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemMsg             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedReply) Reset() {
	*x = FeedReply{}
	mi := &file_internal_sourceplugin_grpc_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedReply) ProtoMessage() {}

func (x *FeedReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sourceplugin_grpc_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedReply.ProtoReflect.Descriptor instead.
func (*FeedReply) Descriptor() ([]byte, []int) {
	return file_internal_sourceplugin_grpc_provider_proto_rawDescGZIP(), []int{5}
}

func (x *FeedReply) GetItems() []*ItemMsg {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *FeedReply) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *FeedReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_sourceplugin_grpc_provider_proto protoreflect.FileDescriptor

const file_internal_sourceplugin_grpc_provider_proto_rawDesc = "" +
	"\n" +
	")internal/sourceplugin/grpc/provider.proto\x12\x0fsourceplugin.v1\"y\n" +
	"\bMediaMsg\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x19\n" +
	"\balt_text\x18\x05 \x01(\tR\aaltText\"\xbc\x03\n" +
	"\aItemMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x12\x1c\n" +
	"\tpermalink\x18\a \x01(\tR\tpermalink\x12\x12\n" +
	"\x04link\x18\b \x01(\tR\x04link\x12/\n" +
	"\x05media\x18\t \x03(\v2\x19.sourceplugin.v1.MediaMsgR\x05media\x12\x14\n" +
	"\x05score\x18\n" +
	" \x01(\x05R\x05score\x12\x1a\n" +
	"\bcomments\x18\v \x01(\x05R\bcomments\x12\x18\n" +
	"\acreated\x18\f \x01(\x03R\acreated\x12\x12\n" +
	"\x04nsfw\x18\r \x01(\bR\x04nsfw\x12\x16\n" +
	"\x06pinned\x18\x0e \x01(\bR\x06pinned\x12\x12\n" +
	"\x04tags\x18\x0f \x03(\tR\x04tags\x12\x1f\n" +
	"\vgroup_count\x18\x10 \x01(\x05R\n" +
	"groupCount\x12\x1d\n" +
	"\n" +
	"group_high\x18\x11 \x01(\x05R\tgroupHigh\"\r\n" +
	"\vKindRequest\"\x1f\n" +
	"\tKindReply\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\"i\n" +
	"\vFeedRequest\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x12\n" +
	"\x04sort\x18\x02 \x01(\tR\x04sort\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"i\n" +
	"\tFeedReply\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.sourceplugin.v1.ItemMsgR\x05items\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\x94\x01\n" +
	"\x0eSourceProvider\x12@\n" +
	"\x04Kind\x12\x1c.sourceplugin.v1.KindRequest\x1a\x1a.sourceplugin.v1.KindReply\x12@\n" +
	"\x04Feed\x12\x1c.sourceplugin.v1.FeedRequest\x1a\x1a.sourceplugin.v1.FeedReplyBFZDgithub.com/go-news-reader/reader/internal/sourceplugin/grpc;sourcepbb\x06proto3"

var (
	file_internal_sourceplugin_grpc_provider_proto_rawDescOnce sync.Once
	file_internal_sourceplugin_grpc_provider_proto_rawDescData []byte
)

func file_internal_sourceplugin_grpc_provider_proto_rawDescGZIP() []byte {
	file_internal_sourceplugin_grpc_provider_proto_rawDescOnce.Do(func() {
		file_internal_sourceplugin_grpc_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_sourceplugin_grpc_provider_proto_rawDesc), len(file_internal_sourceplugin_grpc_provider_proto_rawDesc)))
	})
	return file_internal_sourceplugin_grpc_provider_proto_rawDescData
}

var file_internal_sourceplugin_grpc_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_sourceplugin_grpc_provider_proto_goTypes = []any{
	(*MediaMsg)(nil),    // 0: sourceplugin.v1.MediaMsg
	(*ItemMsg)(nil),     // 1: sourceplugin.v1.ItemMsg
	(*KindRequest)(nil), // 2: sourceplugin.v1.KindRequest
	(*KindReply)(nil),   // 3: sourceplugin.v1.KindReply
	(*FeedRequest)(nil), // 4: sourceplugin.v1.FeedRequest
	(*FeedReply)(nil),   // 5: sourceplugin.v1.FeedReply
}
var file_internal_sourceplugin_grpc_provider_proto_depIdxs = []int32{
	0, // 0: sourceplugin.v1.ItemMsg.media:type_name -> sourceplugin.v1.MediaMsg
	1, // 1: sourceplugin.v1.FeedReply.items:type_name -> sourceplugin.v1.ItemMsg
	2, // 2: sourceplugin.v1.SourceProvider.Kind:input_type -> sourceplugin.v1.KindRequest
	4, // 3: sourceplugin.v1.SourceProvider.Feed:input_type -> sourceplugin.v1.FeedRequest
	3, // 4: sourceplugin.v1.SourceProvider.Kind:output_type -> sourceplugin.v1.KindReply
	5, // 5: sourceplugin.v1.SourceProvider.Feed:output_type -> sourceplugin.v1.FeedReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_sourceplugin_grpc_provider_proto_init() }
func file_internal_sourceplugin_grpc_provider_proto_init() {
	if File_internal_sourceplugin_grpc_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_sourceplugin_grpc_provider_proto_rawDesc), len(file_internal_sourceplugin_grpc_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_sourceplugin_grpc_provider_proto_goTypes,
		DependencyIndexes: file_internal_sourceplugin_grpc_provider_proto_depIdxs,
		MessageInfos:      file_internal_sourceplugin_grpc_provider_proto_msgTypes,
	}.Build()
	File_internal_sourceplugin_grpc_provider_proto = out.File
	file_internal_sourceplugin_grpc_provider_proto_goTypes = nil
	file_internal_sourceplugin_grpc_provider_proto_depIdxs = nil
}
