// Package mediacachepb carries the wire types for the reader's out-of-process
// media-cache plugins. The MediaCache service mirrors mediacache.Cache
// (Get + Put) so a plugin binary can serve a shared/network media cache to the
// host over gRPC.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: internal/mediacacheplugin/grpc/mediacache.proto

package mediacachepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MediaCache_Get_FullMethodName = "/mediacacheplugin.v1.MediaCache/Get"
	MediaCache_Put_FullMethodName = "/mediacacheplugin.v1.MediaCache/Put"
)

// MediaCacheClient is the client API for MediaCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MediaCache is the gRPC face of mediacache.Cache.
type MediaCacheClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutReply, error)
}

type mediaCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaCacheClient(cc grpc.ClientConnInterface) MediaCacheClient {
	return &mediaCacheClient{cc}
}

func (c *mediaCacheClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReply)
	err := c.cc.Invoke(ctx, MediaCache_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaCacheClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutReply)
	err := c.cc.Invoke(ctx, MediaCache_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediaCacheServer is the server API for MediaCache service.
// All implementations must embed UnimplementedMediaCacheServer
// for forward compatibility.
//
// MediaCache is the gRPC face of mediacache.Cache.
type MediaCacheServer interface {
	Get(context.Context, *GetRequest) (*GetReply, error)
	Put(context.Context, *PutRequest) (*PutReply, error)
	mustEmbedUnimplementedMediaCacheServer()
}

// UnimplementedMediaCacheServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediaCacheServer struct{}

func (UnimplementedMediaCacheServer) Get(context.Context, *GetRequest) (*GetReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedMediaCacheServer) Put(context.Context, *PutRequest) (*PutReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedMediaCacheServer) mustEmbedUnimplementedMediaCacheServer() {}
func (UnimplementedMediaCacheServer) testEmbeddedByValue()                    {}

// UnsafeMediaCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaCacheServer will
// result in compilation errors.
type UnsafeMediaCacheServer interface {
	mustEmbedUnimplementedMediaCacheServer()
}

func RegisterMediaCacheServer(s grpc.ServiceRegistrar, srv MediaCacheServer) {
	// If the following call panics, it indicates UnimplementedMediaCacheServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MediaCache_ServiceDesc, srv)
}

func _MediaCache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaCacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaCache_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaCacheServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaCache_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaCacheServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaCache_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaCacheServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MediaCache_ServiceDesc is the grpc.ServiceDesc for MediaCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mediacacheplugin.v1.MediaCache",
	HandlerType: (*MediaCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _MediaCache_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _MediaCache_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/mediacacheplugin/grpc/mediacache.proto",
}
