// Package mediacachepb carries the wire types for the reader's out-of-process
// media-cache plugins. The MediaCache service mirrors mediacache.Cache
// (Get + Put) so a plugin binary can serve a shared/network media cache to the
// host over gRPC.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: internal/mediacacheplugin/grpc/mediacache.proto

package mediacachepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetRequest asks the cache for the bytes stored under a media URL.
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_internal_mediacacheplugin_grpc_mediacache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_mediacacheplugin_grpc_mediacache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_internal_mediacacheplugin_grpc_mediacache_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// GetReply carries the cached bytes and whether a usable entry was found, so a
// miss (found=false) crosses the process boundary cleanly.
type GetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	mi := &file_internal_mediacacheplugin_grpc_mediacache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_mediacacheplugin_grpc_mediacache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_internal_mediacacheplugin_grpc_mediacache_proto_rawDescGZIP(), []int{1}
}

func (x *GetReply) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// PutRequest stores the original bytes for a media URL.
type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_internal_mediacacheplugin_grpc_mediacache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_mediacacheplugin_grpc_mediacache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_internal_mediacacheplugin_grpc_mediacache_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PutRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// PutReply is the (empty) result of MediaCache.Put; Put is best-effort and
// reports nothing.
type PutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutReply) Reset() {
	*x = PutReply{}
	mi := &file_internal_mediacacheplugin_grpc_mediacache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutReply) ProtoMessage() {}

func (x *PutReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_mediacacheplugin_grpc_mediacache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutReply.ProtoReflect.Descriptor instead.
func (*PutReply) Descriptor() ([]byte, []int) {
	return file_internal_mediacacheplugin_grpc_mediacache_proto_rawDescGZIP(), []int{3}
}

var File_internal_mediacacheplugin_grpc_mediacache_proto protoreflect.FileDescriptor

const file_internal_mediacacheplugin_grpc_mediacache_proto_rawDesc = "" +
	"\n" +
	"/internal/mediacacheplugin/grpc/mediacache.proto\x12\x13mediacacheplugin.v1\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"4\n" +
	"\bGetReply\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"2\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\n" +
	"\n" +
	"\bPutReply2\x9a\x01\n" +
	"\n" +
	"MediaCache\x12E\n" +
	"\x03Get\x12\x1f.mediacacheplugin.v1.GetRequest\x1a\x1d.mediacacheplugin.v1.GetReply\x12E\n" +
	"\x03Put\x12\x1f.mediacacheplugin.v1.PutRequest\x1a\x1d.mediacacheplugin.v1.PutReplyBNZLgithub.com/go-news-reader/reader/internal/mediacacheplugin/grpc;mediacachepbb\x06proto3"

var (
	file_internal_mediacacheplugin_grpc_mediacache_proto_rawDescOnce sync.Once
	file_internal_mediacacheplugin_grpc_mediacache_proto_rawDescData []byte
)

func file_internal_mediacacheplugin_grpc_mediacache_proto_rawDescGZIP() []byte {
	file_internal_mediacacheplugin_grpc_mediacache_proto_rawDescOnce.Do(func() {
		file_internal_mediacacheplugin_grpc_mediacache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_mediacacheplugin_grpc_mediacache_proto_rawDesc), len(file_internal_mediacacheplugin_grpc_mediacache_proto_rawDesc)))
	})
	return file_internal_mediacacheplugin_grpc_mediacache_proto_rawDescData
}

var file_internal_mediacacheplugin_grpc_mediacache_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_mediacacheplugin_grpc_mediacache_proto_goTypes = []any{
	(*GetRequest)(nil), // 0: mediacacheplugin.v1.GetRequest
	(*GetReply)(nil),   // 1: mediacacheplugin.v1.GetReply
	(*PutRequest)(nil), // 2: mediacacheplugin.v1.PutRequest
	(*PutReply)(nil),   // 3: mediacacheplugin.v1.PutReply
}
var file_internal_mediacacheplugin_grpc_mediacache_proto_depIdxs = []int32{
	0, // 0: mediacacheplugin.v1.MediaCache.Get:input_type -> mediacacheplugin.v1.GetRequest
	2, // 1: mediacacheplugin.v1.MediaCache.Put:input_type -> mediacacheplugin.v1.PutRequest
	1, // 2: mediacacheplugin.v1.MediaCache.Get:output_type -> mediacacheplugin.v1.GetReply
	3, // 3: mediacacheplugin.v1.MediaCache.Put:output_type -> mediacacheplugin.v1.PutReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_mediacacheplugin_grpc_mediacache_proto_init() }
func file_internal_mediacacheplugin_grpc_mediacache_proto_init() {
	if File_internal_mediacacheplugin_grpc_mediacache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_mediacacheplugin_grpc_mediacache_proto_rawDesc), len(file_internal_mediacacheplugin_grpc_mediacache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_mediacacheplugin_grpc_mediacache_proto_goTypes,
		DependencyIndexes: file_internal_mediacacheplugin_grpc_mediacache_proto_depIdxs,
		MessageInfos:      file_internal_mediacacheplugin_grpc_mediacache_proto_msgTypes,
	}.Build()
	File_internal_mediacacheplugin_grpc_mediacache_proto = out.File
	file_internal_mediacacheplugin_grpc_mediacache_proto_goTypes = nil
	file_internal_mediacacheplugin_grpc_mediacache_proto_depIdxs = nil
}
